name: Build USDX
on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    steps:
      - run: git clone https://github.com/UltraStar-Deluxe/USDX

      - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          manifest-path: ./USDX/dists/flatpak/eu.usdx.UltraStarDeluxe.yaml
          cache-key: flatpak-builder-${{ github.sha }}

      - run: |
          ls -la
          ls -la ./USDX

      - uses: actions/upload-artifact@v2
        with:
          name: Flatpak
          path: app.flatpak
